import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NexCart",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",

  },

};



export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={inter.className} >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          suppressHydrationWarning={true}
        >
          <Navbar  />
          <div className="max-w-7xl mx-auto">{children}</div>
          <Toaster />
          <Footer></Footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
